### PR TITLE
SSSE3->AVX2, NEON32 decoding optimization

### PR DESCRIPTION
**Pull request by mayeut**
Use Wojciech Mula (@WojciechMula) and @aqrit implementation update for
AVX2 / SSSE3 / NEON32 decoding.

SSSE3 implementation is reused in SSE4.1, SSE4.2 and AVX dispatched
decoding loops.

SSE4.2 implementation is now useless but kept to ease integration of
future updates if needed.

Speed-up on i7-4870HQ @ 2.5 GHz (clang-800.0.42.1, x86_64)
SSSE3 decoding: +79%
SSE4.2 decoding: +37%
AVX decoding: +57%
AVX2 decoding: +64%

Speed-up on Apple iPhone SE (clang-800.0.42.1, armv7)
NEON32 decoding: +66%

### CODE REVIEW

**Comment by mayeut** [comment]
@aklomp, this is the last PR of the series mentioned in #35

**Comment by aqrit** [comment]
>lib/arch/ssse3/dec_loop.c:
```
-	if (_mm_movemask_epi8(CMPEQ(_mm_and_si128(lo, hi), 0)) != 0xFFFF) {
+	if (_mm_movemask_epi8(_mm_cmpgt_epi8(_mm_and_si128(lo, hi), 0)) != 0) { 
```
a couple bytes smaller
and has better formatting for any future ffs() of mask

**Comment by mayeut** [comment]
@aqrit, done !

**Comment by aklomp** [comment]
Hey guys, sorry about the delays, I just wanted to say that I haven't forgotten about it. Reviewing this PR has been on my to-do list for the past two weeks. I've been very busy with work, personal life and other distractions, but I hope to sit down and review it soon. Thanks a lot for your efforts to improve this library, I appreciate it and will get back to you soon.

**Comment by mayeut** [comment]
@aklomp, when do you think you'll have time to look at this ?
Thanks

**Comment by aklomp** [comment]
Thanks for setting me straight. I just merged your commit as-is, for these reasons:

- The code passes all tests.
- The speedup is _very_ significant, as I don't need to tell you :-)
- This obvious improvement has been languishing in the PR hole for over half a year, to the detriment of the community.
- I recently pushed some changes to master and it felt unfair to not address your PR first.
- I can't expect you to keep rebasing your work every time I make a change, and you're right to ask for progress.
- I couldn't live with myself any more ;-)

A very big **Thank You** to you, @aqrit and @WojciechMula for your contributions and your patience.

Some justification for not merging sooner:
- I honestly have a hard time understanding what's going on in the new algorithm. The description is not super clear. Perhaps you've hit the limit of what I can mentally grok. I'd like to understand code before I merge it, but in the end I decided to merge it anyway because the tests pass. I can invest time in understanding it later, for now let's have it in.
- I don't like certain stylistic choices in the code. This ranges from naming of variables to use of whitespace and the fact that the SSE4.x codecs are now the SSSE3 codecs in disguise. This threw up a big mental barrier to review. I've decided now to accept what we have, and perhaps rework parts of the code later as I go through it to understand it better.

I think the work could perhaps have been presented in a way that would have made it easier to accept for me, but that's a very entitled standpoint. I'm really grateful for all of the work you've done for this project, and the fact that you've decided to contribute at all.

Sorry it took this long. I guess I could make excuses, but in the end I'm really to blame. Thanks again, and on to the next PR!

**Comment by WojciechMula** [comment]
@aklomp If you like, you might take a look at our paper https://arxiv.org/abs/1704.00605 - @lemire did a great job describing the algorithms in details. I agree they're tricky. :)

I'm really glad to see that our algorithms gained real-world users. :)

**Comment by lemire** [comment]
+1

**Pull request merged**
